// <auto-generated />
using System;
using DeliveryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319132850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Москва, ул. Ленина 1",
                            Email = "ivan@mail.ru",
                            FullName = "Иван Петров",
                            Phone = "79001234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Москва, ул. Пушкина 5",
                            Email = "maria@mail.ru",
                            FullName = "Мария Сидорова",
                            Phone = "79007654321"
                        });
                });

            modelBuilder.Entity("DeliveryApi.Models.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Couriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Алексей Курьеров",
                            IsAvailable = true,
                            Phone = "79009876543",
                            Vehicle = "Велосипед"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Дмитрий Быстров",
                            IsAvailable = true,
                            Phone = "79001112233",
                            Vehicle = "Мотоцикл"
                        });
                });

            modelBuilder.Entity("DeliveryApi.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("CourierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CourierId");

                    b.HasIndex("RouteId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CourierId = 1,
                            CreatedAt = new DateTime(2026, 3, 19, 13, 28, 50, 1, DateTimeKind.Utc).AddTicks(3655),
                            RouteId = 1,
                            Status = "InTransit",
                            TrackingNumber = "TRK001",
                            WeightKg = 2.5
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CourierId = 2,
                            CreatedAt = new DateTime(2026, 3, 19, 13, 28, 50, 1, DateTimeKind.Utc).AddTicks(4059),
                            RouteId = 2,
                            Status = "Pending",
                            TrackingNumber = "TRK002",
                            WeightKg = 0.80000000000000004
                        });
                });

            modelBuilder.Entity("DeliveryApi.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceKm = 12.5,
                            EndPoint = "Район Северный",
                            Name = "Маршрут А",
                            StartPoint = "Склад Центральный"
                        },
                        new
                        {
                            Id = 2,
                            DistanceKm = 18.300000000000001,
                            EndPoint = "Район Южный",
                            Name = "Маршрут Б",
                            StartPoint = "Склад Центральный"
                        });
                });

            modelBuilder.Entity("DeliveryApi.Models.Package", b =>
                {
                    b.HasOne("DeliveryApi.Models.Client", "Client")
                        .WithMany("Packages")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryApi.Models.Courier", "Courier")
                        .WithMany("Packages")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryApi.Models.Route", "Route")
                        .WithMany("Packages")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Courier");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("DeliveryApi.Models.Client", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("DeliveryApi.Models.Courier", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("DeliveryApi.Models.Route", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
