{
 "title": "HTTP запросов в секунду",
 "time": { "from": "2026-03-18T11:48:32.936Z", "to": "2026-03-20T11:48:32.936Z" },
 "panels": [
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_active_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_requests_per_second_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}